# Generated by Django 3.1.3 on 2020-11-21 16:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secure_resource', '0003_auto_20201121_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='securefile',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='securefile',
            name='visited',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='secureurl',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='secureurl',
            name='visited',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
