# Generated by Django 3.1.3 on 2020-11-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secure_resource', '0004_auto_20201121_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileredirect',
            old_name='expires_in',
            new_name='expires_at',
        ),
        migrations.RenameField(
            model_name='urlredirect',
            old_name='expires_in',
            new_name='expires_at',
        ),
    ]
