# Generated by Django 3.1.3 on 2020-11-22 14:40
import os
from django.contrib.auth import get_user_model
from django.db import migrations

DEFAULT_SUPERUSER_NAME = os.environ.get("ADMIN_USER", default="admin")
DEFAULT_SUPERUSER_EMAIL = os.environ.get("ADMIN_EMAIL", default="admin@admin.com")
DEFAULT_SUPERUSER_PASSWORD = os.environ.get(
    "ADMIN_PASSWORD", default="5uper-S3cret_p4ssw0rd!"
)


def create_superuser(apps, schema_editor):
    User = get_user_model()
    User.objects.create_superuser(
        DEFAULT_SUPERUSER_NAME,  # username
        DEFAULT_SUPERUSER_EMAIL,  # email
        DEFAULT_SUPERUSER_PASSWORD,  # password
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [migrations.RunPython(create_superuser)]
