# Generated by Django 3.1.3 on 2020-11-21 12:59

from django.db import migrations, models
import django.db.models.deletion
import secure_resource.models


class Migration(migrations.Migration):

    dependencies = [
        ('secure_resource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UrlRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_in', models.DateTimeField(default=secure_resource.models.set_expiration_date)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect', to='secure_resource.secureurl')),
            ],
        ),
        migrations.CreateModel(
            name='FileRedirect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires_in', models.DateTimeField(default=secure_resource.models.set_expiration_date)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redirect', to='secure_resource.securefile')),
            ],
        ),
    ]
