# Generated by Django 3.1.3 on 2020-11-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secure_resource', '0002_fileredirect_urlredirect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileredirect',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redirect', to='secure_resource.securefile'),
        ),
        migrations.AlterField(
            model_name='urlredirect',
            name='source',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='redirect', to='secure_resource.secureurl'),
        ),
    ]
